BEGIN;
CREATE TABLE `distribucion_companiaelectrica` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `nombre` varchar(50) NOT NULL);
CREATE TABLE `distribucion_energiaproducidadiaria` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `cantidad` double precision NOT NULL, `fecha_entrega` datetime NOT NULL);
CREATE TABLE `distribucion_envioenergiaextra` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `volumen_energia` double precision NOT NULL);
CREATE TABLE `distribucion_estacionprimaria` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `nombre` varchar(50) NOT NULL UNIQUE, `num_transformadores` integer NOT NULL);
CREATE TABLE `distribucion_linea` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `numero_linea` varchar(10) NOT NULL);
CREATE TABLE `distribucion_provincia` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `codigo` varchar(10) NOT NULL, `nombre` varchar(50) NOT NULL);
CREATE TABLE `distribucion_reddistribucion` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `numero_red` integer NOT NULL, `cabezera_id` integer NOT NULL);
CREATE TABLE `distribucion_subestacion` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `linea_abastecimiento_id` integer NOT NULL);
CREATE TABLE `distribucion_zonaservicio` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `consumo_promedio` double precision NOT NULL, `consumidores_particulares` integer NOT NULL, `consumidores_empresas` integer NOT NULL, `consumidores_instituciones` integer NOT NULL);
CREATE TABLE `distribucion_zonaservicio_subestacion_distribuidora` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `zonaservicio_id` integer NOT NULL, `subestacion_id` integer NOT NULL, UNIQUE (`zonaservicio_id`, `subestacion_id`));
ALTER TABLE `distribucion_provincia` ADD COLUMN `zona_servicio_id` integer NOT NULL;
ALTER TABLE `distribucion_provincia` ALTER COLUMN `zona_servicio_id` DROP DEFAULT;
ALTER TABLE `distribucion_linea` ADD COLUMN `red_distribucion_perteneciente_id` integer NOT NULL;
ALTER TABLE `distribucion_linea` ALTER COLUMN `red_distribucion_perteneciente_id` DROP DEFAULT;
ALTER TABLE `distribucion_envioenergiaextra` ADD COLUMN `red_enviante_id` integer NOT NULL;
ALTER TABLE `distribucion_envioenergiaextra` ALTER COLUMN `red_enviante_id` DROP DEFAULT;
ALTER TABLE `distribucion_envioenergiaextra` ADD COLUMN `red_receptora_id` integer NOT NULL;
ALTER TABLE `distribucion_envioenergiaextra` ALTER COLUMN `red_receptora_id` DROP DEFAULT;
ALTER TABLE `distribucion_energiaproducidadiaria` ADD COLUMN `estacion_primaria_id` integer NOT NULL;
ALTER TABLE `distribucion_energiaproducidadiaria` ALTER COLUMN `estacion_primaria_id` DROP DEFAULT;
ALTER TABLE `distribucion_energiaproducidadiaria` ADD COLUMN `productor_id` integer NOT NULL;
ALTER TABLE `distribucion_energiaproducidadiaria` ALTER COLUMN `productor_id` DROP DEFAULT;
CREATE TABLE `distribucion_companiaelectrica_redes_distribucion_propietarias` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `companiaelectrica_id` integer NOT NULL, `reddistribucion_id` integer NOT NULL, UNIQUE (`companiaelectrica_id`, `reddistribucion_id`));
ALTER TABLE `distribucion_reddistribucion` ADD CONSTRAINT `D3d59760c59e20dc7b83323a77ed9729` FOREIGN KEY (`cabezera_id`) REFERENCES `distribucion_estacionprimaria` (`id`);
ALTER TABLE `distribucion_subestacion` ADD CONSTRAINT `D12f669111d8ed01fb3cd0d14b29f7fe` FOREIGN KEY (`linea_abastecimiento_id`) REFERENCES `distribucion_linea` (`id`);
ALTER TABLE `distribucion_zonaservicio_subestacion_distribuidora` ADD CONSTRAINT `D4682a2bc27a1ec63234cd482e0896b7` FOREIGN KEY (`zonaservicio_id`) REFERENCES `distribucion_zonaservicio` (`id`);
ALTER TABLE `distribucion_zonaservicio_subestacion_distribuidora` ADD CONSTRAINT `d_subestacion_id_3964033cb163a3d7_fk_distribucion_subestacion_id` FOREIGN KEY (`subestacion_id`) REFERENCES `distribucion_subestacion` (`id`);
CREATE INDEX `distribucion_provincia_1546aca2` ON `distribucion_provincia` (`zona_servicio_id`);
ALTER TABLE `distribucion_provincia` ADD CONSTRAINT `D4ed492e1793ad902b3114d1bdd3ca2c` FOREIGN KEY (`zona_servicio_id`) REFERENCES `distribucion_zonaservicio` (`id`);
CREATE INDEX `distribucion_linea_81942fa5` ON `distribucion_linea` (`red_distribucion_perteneciente_id`);
ALTER TABLE `distribucion_linea` ADD CONSTRAINT `aff5092e4d2a651490dcfd005fcb90f6` FOREIGN KEY (`red_distribucion_perteneciente_id`) REFERENCES `distribucion_reddistribucion` (`id`);
CREATE INDEX `distribucion_envioenergiaextra_38772411` ON `distribucion_envioenergiaextra` (`red_enviante_id`);
ALTER TABLE `distribucion_envioenergiaextra` ADD CONSTRAINT `D2d28db66d8759fd38f6b0a57c3e123a` FOREIGN KEY (`red_enviante_id`) REFERENCES `distribucion_reddistribucion` (`id`);
CREATE INDEX `distribucion_envioenergiaextra_578f30de` ON `distribucion_envioenergiaextra` (`red_receptora_id`);
ALTER TABLE `distribucion_envioenergiaextra` ADD CONSTRAINT `a301046038de7316afbe6c9f08a9a2cc` FOREIGN KEY (`red_receptora_id`) REFERENCES `distribucion_reddistribucion` (`id`);
CREATE INDEX `distribucion_energiaproducidadiaria_27e8ae54` ON `distribucion_energiaproducidadiaria` (`estacion_primaria_id`);
ALTER TABLE `distribucion_energiaproducidadiaria` ADD CONSTRAINT `cf78b081d45e620e3a85566ebeda06b2` FOREIGN KEY (`estacion_primaria_id`) REFERENCES `distribucion_estacionprimaria` (`id`);
CREATE INDEX `distribucion_energiaproducidadiaria_b6090adb` ON `distribucion_energiaproducidadiaria` (`productor_id`);
ALTER TABLE `distribucion_energiaproducidadiaria` ADD CONSTRAINT `distribucio_productor_id_afc2c59ce506c4c_fk_energia_productor_id` FOREIGN KEY (`productor_id`) REFERENCES `energia_productor` (`id`);
ALTER TABLE `distribucion_companiaelectrica_redes_distribucion_propietarias` ADD CONSTRAINT `D0dfa2d8338874c80716ebec6b45a379` FOREIGN KEY (`companiaelectrica_id`) REFERENCES `distribucion_companiaelectrica` (`id`);
ALTER TABLE `distribucion_companiaelectrica_redes_distribucion_propietarias` ADD CONSTRAINT `D4d2a334cfc4918283583d04a9fb8777` FOREIGN KEY (`reddistribucion_id`) REFERENCES `distribucion_reddistribucion` (`id`);

COMMIT;